version: '3'

networks:
  bmohor.42.fr:
    name: bmohor.42.fr
    driver: bridge 

volumes:
  mdb:
    driver: local
    driver_opts:
      device: home/bmohor/data/mdb
  wp:
    driver: local
    driver_opts:
      device: home/bmohor/data/wp

services:
  mysql:
    build:
      context: srcs/mariadb
    env_file: .env
    image: mariaDB
    ports:
      - "3306:3306"
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - bmohor.42.fr
    restart: always
  
  wordpress:
    build:
      context: srcs/wordpress
    image: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/bmohorwp
    networks:
      - bmohor.42.fr
    restart: always

  nginx:
    build:
      context: srcs/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/bmohorstuff
    networks:
      - bmohor.42.fr
    links:
      - wordpress
    restart: always
