version: '3'

networks:
  bmohor.42.fr:
    name: bmohor.42.fr
    driver: bridge 

volumes:
  mdb:
    driver: local
    driver_opts:
      type: none
      device: /home/bmohor/data/msq/
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/bmohor/data/wp/

services:
  mysql:
    build:
      context: requirements/mariadb
    image: mariadb
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - bmohor.42.fr
    restart: always
  
  wordpress:
    build:
      context: requirements/wordpress
      args:
        U: ${MSQL_US}
        P: ${MSQL_PASS}
        W: ${WP_BASE}
        B: ${COUNT_MDB}
    env_file:
      - .env
    image: wordpress
    volumes:
      - wp:/var/www/bmohorwp
    networks:
      - bmohor.42.fr
    restart: always

  nginx:
    build:
      context: requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/bmohorstuff
    networks:
      - bmohor.42.fr
    links:
      - wordpress
    restart: always
